### PR TITLE
[WIP] Fix: time out condition on absolute time interval since start

### PR DESCRIPTION
**Pull request by asfaltboy**
This solution is imperfect since the test doesn't seem to stop running,
or at the very least the status still shows "Testing GitSavvy":

screen shot 2017-06-24 at 15 47 48

Related to #55

### CODE REVIEW

**Comment by randy3k** [comment]
should be fixed by https://github.com/randy3k/UnitTesting/commit/6990ade9185f2102f40099dfc1a211a4524170ef

**Comment by asfaltboy** [comment]
@randy3k seems to work well, times out after 10

**Comment by randy3k** [comment]
Of course, it should be customizable. May be something like `yield (condition, timeout)`.

**Comment by asfaltboy** [comment]
That's also a good idea, and the tuple form can be optional (handled via `isinstance(tuple)`).

Though, I'd still like to be able to config e.g 2 across all projects without changing code, if that's possible.

**Pull request closed without merging**
